"""Deterministic analog topology generation, circuit graphs, and layout evidence."""

from topology_lantern._version import __version__
from topology_lantern.benchmark import benchmark_json, sizing_benchmark
from topology_lantern.circuit import (
    CircuitDevice,
    CircuitElementKind,
    CircuitGraph,
    CircuitGraphError,
    CircuitInstance,
    CircuitNet,
    CircuitPort,
    CircuitScope,
    SourceLocation,
    circuit_graph_json,
)
from topology_lantern.circuit_benchmark import circuit_ingest_benchmark
from topology_lantern.emit import candidate_spice, result_json, result_text
from topology_lantern.explain import explain_candidate, verify_replay
from topology_lantern.layout import (
    ConstraintOrigin,
    InferenceLimits,
    LayoutConstraint,
    LayoutConstraintError,
    LayoutConstraintKind,
    LayoutConstraintSet,
    LayoutInferenceReport,
    infer_layout_constraints,
    layout_constraints_json,
    layout_inference_report,
    layout_report_json,
    load_layout_constraints,
    parse_layout_constraints,
    validate_layout_conflicts,
)
from topology_lantern.search import generate_candidates
from topology_lantern.sequence_baseline import (
    BaselineEvaluationReport,
    BaselineSampleReport,
    CompactRuleSequence,
    SequenceBaselineCheckpoint,
    SequenceBaselineError,
    SequenceExample,
    build_sequence_examples,
    encode_rule_sequence,
    evaluate_sequence_baseline,
    evaluation_report_json,
    load_sequence_checkpoint,
    parse_sequence_checkpoint,
    replay_compact_sequence,
    sample_report_json,
    sample_sequence_baseline,
    sequence_checkpoint_json,
    spec_lineage_id,
    split_sequence_examples,
    train_sequence_baseline,
)
from topology_lantern.spec import DesignSpec, Objectives, SearchLimits
from topology_lantern.spice import IngestLimits, load_spice, parse_spice
from topology_lantern.types import Candidate, GenerationResult, SpecError

__all__ = [
    "BaselineEvaluationReport",
    "BaselineSampleReport",
    "Candidate",
    "CircuitDevice",
    "CircuitElementKind",
    "CircuitGraph",
    "CircuitGraphError",
    "CircuitInstance",
    "CircuitNet",
    "CircuitPort",
    "CircuitScope",
    "CompactRuleSequence",
    "ConstraintOrigin",
    "DesignSpec",
    "GenerationResult",
    "InferenceLimits",
    "IngestLimits",
    "LayoutConstraint",
    "LayoutConstraintError",
    "LayoutConstraintKind",
    "LayoutConstraintSet",
    "LayoutInferenceReport",
    "Objectives",
    "SearchLimits",
    "SequenceBaselineCheckpoint",
    "SequenceBaselineError",
    "SequenceExample",
    "SourceLocation",
    "SpecError",
    "__version__",
    "benchmark_json",
    "build_sequence_examples",
    "candidate_spice",
    "circuit_graph_json",
    "circuit_ingest_benchmark",
    "encode_rule_sequence",
    "evaluate_sequence_baseline",
    "evaluation_report_json",
    "explain_candidate",
    "generate_candidates",
    "infer_layout_constraints",
    "layout_constraints_json",
    "layout_inference_report",
    "layout_report_json",
    "load_layout_constraints",
    "load_sequence_checkpoint",
    "load_spice",
    "parse_layout_constraints",
    "parse_sequence_checkpoint",
    "parse_spice",
    "replay_compact_sequence",
    "result_json",
    "result_text",
    "sample_report_json",
    "sample_sequence_baseline",
    "sequence_checkpoint_json",
    "sizing_benchmark",
    "spec_lineage_id",
    "split_sequence_examples",
    "train_sequence_baseline",
    "validate_layout_conflicts",
    "verify_replay",
]
